### ISSUE TITLE
El horario no se visualiza correctamente en versión móvil

### ISSUE THREAD

**Issue by cua-cua** [python-vigo/pyday-2016#9]
Hola, 
Al abrir la página con el móvil, el horario aparece pegado al borde derecho y se corta (no deja ver más), y la fecha en línea. Adjunto capturas de pantalla. 

![photo208383477126637917](https://cloud.githubusercontent.com/assets/6835191/18029760/802d0444-6ca1-11e6-9676-34091d877025.jpg)
![photo208383477126637916](https://cloud.githubusercontent.com/assets/6835191/18029762/83dde838-6ca1-11e6-9aa1-e6efcc342986.jpg)

**Comment by dibanez** [comment]
Si, voy a preparar una tabla responsive para el horario.

**Comment by dibanez** [comment]
En la pull request #13 se soluciona ese problema.
